# frozen_string_literal: true

module Reports
  class BaseController < ApplicationController
    include DateRangeFilter

    before_action :authorize_reports

    helper_method :report_title, :report_description

    private

    def authorize_reports
      authorize :report, :index?
    end

    def report_title
      "Report"
    end

    def report_description
      nil
    end

    # CSV export helpers
    def send_csv(data, filename)
      send_data data,
                type: "text/csv; charset=utf-8",
                disposition: "attachment",
                filename: "#{filename}_#{Date.current.iso8601}.csv"
    end

    # PDF export helpers
    def send_pdf(document, filename)
      send_data document.render,
                type: "application/pdf",
                disposition: "attachment",
                filename: "#{filename}_#{Date.current.iso8601}.pdf"
    end

    # Standard PDF header with organization branding
    def pdf_header(pdf, title, subtitle = nil)
      branding = current_organization&.branding
      primary_color = branding&.primary_color&.delete("#") || "0d6efd"

      # Organization logo or name
      if branding&.logo&.attached?
        begin
          logo_path = ActiveStorage::Blob.service.path_for(branding.logo.blob.key)
          pdf.image logo_path, height: 30, position: :left
          pdf.move_down 10
        rescue StandardError
          # Fall back to text if logo can't be loaded
          pdf.text current_organization.name, size: 14, style: :bold, color: primary_color
          pdf.move_down 5
        end
      else
        pdf.text current_organization.name, size: 14, style: :bold, color: primary_color
        pdf.move_down 5
      end

      pdf.text title, size: 24, style: :bold
      pdf.text subtitle, size: 12, color: "666666" if subtitle
      pdf.text "Generated: #{Time.current.strftime('%B %d, %Y at %I:%M %p')}", size: 10, color: "999999"
      pdf.move_down 20
    end

    # Standard PDF footer with branding
    def pdf_footer(pdf)
      branding = current_organization&.branding

      pdf.move_down 30
      pdf.text "Confidential - For internal use only", size: 8, color: "999999", align: :center

      # Custom report footer text or default
      footer_text = branding&.report_footer_text.presence || "Generated by #{PlatformBrand.name}"
      pdf.text footer_text, size: 8, color: "999999", align: :center

      # Powered by text if enabled
      if branding&.show_powered_by? != false
        pdf.text PlatformBrand.powered_by_text, size: 8, color: "999999", align: :center
      end
    end

    # Filter params for query objects
    def filter_params
      {
        start_date: start_date,
        end_date: end_date,
        job_id: params[:job_id].presence,
        department_id: params[:department_id].presence,
        source_type: params[:source_type].presence
      }.compact
    end
  end
end
